# Build application
FROM node:24.14.0-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./

COPY frontend/package.json frontend/
COPY backend/package.json backend/

RUN npm ci

COPY . .

RUN npm run build:backend

# Start application
FROM node:24.14.0-alpine AS runner

WORKDIR /app

COPY --from=builder /app/backend/dist ./dist

COPY backend/package.json ./

RUN npm install

EXPOSE 5000

CMD ["node", "dist/server.js"]
