# Build application
FROM node:24.14.0-alpine AS builder

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /app
COPY package.json package-lock.json ./

COPY frontend/package.json frontend/
COPY backend/package.json backend/

RUN npm ci

COPY frontend ./frontend

RUN npm run build:frontend

# Serve with nginx
FROM nginx:stable-alpine AS runner

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
