services:
  postgresql:
    container_name: coursedb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  backend:
    container_name: task-backend
    image: task-backend
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"

  frontend:
    container_name: task-frontend
    image: task-frontend
    restart: always
    ports:
      - "5173:80"

volumes:
  db_data:
