name: Lint test audit

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    branches:
      - main

jobs:
  list_test_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install project dependencies
        run: npm run install:all

      - name: Run linting for backend
        run: npm run lint:backend

      - name: Run testing for backend
        run: npm run test:backend

      - name: Run audit for backend
        working-directory: ./backend
        run: npm audit --audit-level=critical

      - name: Build backend docker image
        run: docker build -f Dockerfile.backend -t task-backend .

      - name: Run linting for frontend
        run: npm run lint:frontend

      - name: Run testing for frontend
        run: npm run test:frontend

      - name: Run audit for frontend
        working-directory: ./frontend
        run: npm audit --audit-level=critical

      - name: Build frontend docker image
        run: docker build -f Dockerfile.frontend --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} -t task-frontend .
      
      - name: Deploy backend to Render
        if: startsWith(github.ref, 'refs/tags/')
        env:
          backend_deploy_url: ${{ secrets.BACKEND_DEPLOY_HOOK_URL }}
        run: |
          curl "$backend_deploy_url"

      - name: Deploy frontend to Render
        if: startsWith(github.ref, 'refs/tags/')
        env:
          frontend_deploy_url: ${{ secrets.FRONTEND_DEPLOY_HOOK_URL }}
        run: |
          curl "$frontend_deploy_url"
